version: '3.1'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: postgres_benchmark
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MAX_CONNECTIONS: 200
    volumes:
      - pgdata_benchmark:/var/lib/postgresql/data
volumes:
  pgdata_benchmark:
